#!/usr/bin/env bash

# Get the current pane's working directory from tmux
CURRENT_DIR=$(tmux display-message -p -F "#{pane_current_path}")

# Fallback to $PWD if not running inside tmux
CURRENT_DIR=${CURRENT_DIR:-$PWD}

if [[ $# -eq 1 ]]; then
    selected=$1
else
# Standard directories + current directory
regular_dirs=$(find ~/projects ~/media ~/documents ~/downloads "$CURRENT_DIR" \
    -not -path "$CURRENT_DIR/.*" -mindepth 1 -maxdepth 2 -type d 2>/dev/null)

# Dot directory exception
config_dirs=$(find ~/.config -mindepth 1 -maxdepth 2 -type d 2>/dev/null)

selected=$(printf "%s\n%s" "$regular_dirs" "$config_dirs" | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

tmux switch-client -t $selected_name
